services:
    app:
        build:
            context: .
        hostname: account-service
        ports:
            - "8001:8001"
        env_file:
            - dev.env
        profiles:
            - app
        depends_on:
            database:
                condition: service_healthy
            discovery:
                condition: service_healthy
        develop:
            watch:
                - action: rebuild
                  path: ./internal
    database:
        image: postgres:16.1-alpine3.18
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: db
        ports:
            - "5432:5432"
        healthcheck:
            test: ["CMD-SHELL", "pg_isready", "-d", "db"]
            timeout: 5s
            retries: 10
    discovery:
        image: consul:1.15.4
        ports:
            - "8500:8500"
        profiles:
            - app
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8500"]
            timeout: 3s
            retries: 10
    discovery-host:
        image: consul:1.15.4
        network_mode: host
        profiles:
            - discovery
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8500"]
            timeout: 3s
            retries: 10
